name: type_ahead
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc_test: ^9.1.0
  formz: ^0.4.1
  easy_localization: ^3.0.1
  hive_flutter: ^1.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  rxdart: ^0.27.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
